### PR TITLE
Update project execution method to Docker

### PR DESCRIPTION
**Pull request by the-mzakrzewski**
#29

The execution method of the project was changed from `npm run dev` to Docker. New Docker configuration files were added, and the README.md file was updated to reflect these changes. This enables a more uniform development environment and makes the project easier to run.

### CODE REVIEW

**Comment by the-mzakrzewski** [comment]
@eddiejaoude I only made this change for local env because I do not know how the deploy process looks.

**Review by eddiejaoude — APPROVED** [review]
Looks great! Thank you 👍

**Comment by eddiejaoude** [comment]
> @ eddiejaoude I only made this change for local env because I do not know how the deploy process looks.

Thank you 👍  The deployment will be the same as the other EddieHub projects, we will use a GH Action to deploy to Caprover, any questions let me know

**Comment by the-mzakrzewski** [comment]
> > @ eddiejaoude I only made this change for local env because I do not know how the deploy process looks.
> 
> Thank you 👍 The deployment will be the same as the other EddieHub projects, we will use a GH Action to deploy to Caprover, any questions let me know

so I will prepare a production Image too

**Comment by eddiejaoude** [comment]
Thanks @the-mzakrzewski .

Q. Any reason why GitHub Actions fail with these changes?

**Comment by the-mzakrzewski** [comment]
@eddiejaoude for now I don't have any idea, my changes shouldn't impact GitHubActions, I will let you know if I find a solution.

**Comment by eddiejaoude** [comment]
No problem @the-mzakrzewski , I was also checking with Pradumna, we don't think it is related.

**Pull request merged**
