### PR TITLE
feat: Added additional property check for homepage in description

### LINKED ISSUE #46: BUG: Description warning when repo URL is empty
### Description

In the "description" check, it checks if the repo url exists in the description, but when the "url" is empty it should not perform this check

This condition should also have the extra condition added `repo.homepage.length > 0`
https://github.com/EddieHubCommunity/HealthCheck/blob/8222a29b6be780801cbf979cf5e4608822d83c20/src/utils/checks/description.js#L36

Making the final line become

```diff
- if (repo.description.includes(repo.homepage)) {
+ if (repo.homepage.length > 0 && repo.description.includes(repo.homepage)) {
```

### Screenshots

Screenshot 2024-07-21 at 19 04 09

### Additional information

You can visit this page on `http://localhost:3000/account/repo/report/{ID}`

### PR DESCRIPTION
**Pull request by wotta**
## Fixes Issue

Added mentioned fix to description file.
Closes #46 

## Changes proposed

- Added length check for the `repo.homepage` property before the `includes` check.
  - This makes sure the check only moved to the `includes` check when the `homepage` is filled.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Thank you for the contribution. Can you comment on the issue so we can assign it to you, this avoids any confusion with other contributors.

The changes look good, is the PR meant to be in `draft`?

**Comment by wotta** [comment]
Yeah it was meant as a draft pr atm @eddiejaoude. Wanted to check if I could add a test to validate the behavior in question.

**Comment by eddiejaoude** [comment]
Thank you for checking about the tests! We have Playwright setup but for the authenticated pages, we are setting that up next week. 

So don't worry about the tests for now, we will have to go back and write the tests once we can mock the GitHub OAuth login with Playwright

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
